version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-107-21-99-237.compute-1.amazonaws.com
            port: '5432'
            database: d5vgii160h3qfs
            ssl: true
            user: fdzonggklsmknd
            password: 77f57d12e00e515b101df9c901ba8d7cfc7394792cd7d294c732be7da2609a39
            migrations: true